import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Geist, Geist_Mono } from "next/font/google";
// import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import "./globals.css";
import ReactToastContainer from "@/components/ReactToastContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <ReactQueryProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <Toaster /> */}
          <ReactToastContainer/>
          {children}
        </body>
      </ReactQueryProvider>
    </html>
  );
}
